//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbour
    {
        public int NeighId { get; set; }
        public Nullable<int> SpotId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> ArriveT { get; set; }
        public Nullable<System.DateTime> LeaveT { get; set; }
        public string Note { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
